version: '3.1'

services:

  bugatti-database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
     - ./configs.env
    networks:
      - bugatti-net
    ports:
      - "3306:3306"
    volumes:
      - bugatti-database-volume:/var/lib/mysql
      - ./scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

  bugatti-adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - bugatti-net

networks:
  bugatti-net:
    external: true

volumes:
  bugatti-database-volume:
    external: true